# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0c5c2732c97102129134a35e4096d1a7f62281c00265c002aa088a36db4652e5c8eec4248343cece56a240ba23c41ae4aeb0959ed1199ddc807f466180c1f444

test:
  secret_key_base: 35c72accd352622affff8fdd3e54c54043bf822fd3f62bacb42ffa8a17b3a1f1b43df6b2e8d5193e7df7a0017d01da59ea8c7baa162e14dd2b9fac89c4f4e5ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
